In [22]:
import torch

In [23]:
x = torch.empty(5, 3)

In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.1973,  0.0125,  0.3045],
        [ 0.0228,  0.3151,  0.6424],
        [ 0.0937,  0.0725,  0.5241],
        [ 0.5381,  0.8339,  0.8295],
        [ 0.3601,  0.1258,  0.8380]])


In [25]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [26]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [1]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable

ModuleNotFoundError: No module named 'matplotlib._path'

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data.astype(np.float32))
tensor2array = torch_data.numpy()
print('numpy array:', np_data,)          
print('\ntorch tensor:', torch_data,)
print('\ntensor to array:', tensor2array)

numpy array: [[0 1 2]
 [3 4 5]]

torch tensor: tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])

tensor to array: [[0. 1. 2.]
 [3. 4. 5.]]


In [57]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([ 1.,  2.,  1.,  2.])


In [58]:
tensor.size()

torch.Size([4])

In [64]:
tensor = torch.FloatTensor([[1,2],[3,4]])            # build a tensor
tensor1 = torch.FloatTensor([[3, 4], [5, 6]])
variable = Variable(tensor, requires_grad=True)      # build a variable, usually for compute gradients
var1 = Variable(tensor1, requires_grad=True)

In [65]:
print(tensor)       # [torch.FloatTensor of size 2x2]
print(variable)     # [torch.FloatTensor of size 2x2]
print(var1)

tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 3.,  4.],
        [ 5.,  6.]])


In [68]:
t_out = torch.mean(tensor*tensor1)       # x^2
v_out = torch.mean(variable*var1)   # x^2
print(t_out)
print(v_out) 

tensor(12.5000)
tensor(12.5000)


In [69]:
v_out.backward()    # backpropagation from v_out
# v_out = 1/4 * sum(variable*variable)
# the gradients w.r.t the variable, d(v_out)/d(variable) = 1/4*2*variable = variable/2
print(variable.grad)
print(var1.grad)


print(variable)     # this is data in variable format


print(variable.data)    # this is data in tensor format


print(variable.data.numpy())    # numpy format

tensor([[ 1.5000,  2.0000],
        [ 2.5000,  3.0000]])
tensor([[ 0.5000,  1.0000],
        [ 1.5000,  2.0000]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])
[[1. 2.]
 [3. 4.]]


In [36]:
matplotlib.__version__

'1.5.1'

In [20]:
x = torch.unsqueeze(torch.linspace(-1, 1, 100), dim=1)  # x data (tensor), shape=(100, 1)
y = x.pow(2) + 0.2*torch.rand(x.size())

In [21]:
X = Variable(x, requires_grad=True)
Y = Variable(y)

In [22]:
class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden1, n_hidden2, n_output):
        super(Net, self).__init__()
        self.hidden1 = torch.nn.Linear(n_feature, n_hidden1)   # hidden layer
        self.hidden2 = torch.nn.Linear(n_hidden1, n_hidden2)
        self.output = torch.nn.Linear(n_hidden2, n_output)

    def forward(self, x):
        x = F.relu(self.hidden1(x))
        x = F.relu(self.hidden2(x))
        x = self.output(x)             # linear output
        return x

In [23]:
net = Net(n_feature=1, n_hidden1=10, n_hidden2=10, n_output=1)     # define the network
print(net)  # net architecture

Net(
  (hidden1): Linear(in_features=1, out_features=10, bias=True)
  (hidden2): Linear(in_features=10, out_features=10, bias=True)
  (output): Linear(in_features=10, out_features=1, bias=True)
)


In [24]:
optimizer = torch.optim.Adam(net.parameters(), lr=0.2)
loss_func = torch.nn.MSELoss()

In [28]:
for t in range(200):
    prediction = net(X)     # input x and predict based on x

    loss = loss_func(prediction, Y)     # must be (1. nn output, 2. target)

    optimizer.zero_grad()   # clear gradients for next train
    loss.backward()         # backpropagation, compute gradients
    optimizer.step()        # apply gradients


In [29]:
loss.data.numpy()

array(0.004601, dtype=float32)