In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [3]:
df_left = DataFrame({'key': ['X','Y','Z','X','Y'],
                  'data': range(5)})

In [4]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [5]:
df_right  = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])

In [6]:
df_right

group_data
X          10
Y          20

In [9]:
pd.merge(df_left, df_right, left_on='key', right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [10]:
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [13]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [14]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [15]:
pd.merge(df_left_hr, df_right_hr, left_on=['key1', 'key2'], right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [16]:
df_left.join(df_right)

key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

In [17]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [18]:
df_right

group_data
X          10
Y          20

In [2]:
dframe = DataFrame({'key1': ['A'] * 2 + ['B'] * 3,
                  'key2': [2, 2, 2, 3, 3]})

In [4]:
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [5]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [6]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [7]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [8]:
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [12]:
dframe.drop_duplicates(['key1'], keep='last')

key1  key2
1    A     2
4    B     3

In [20]:
dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                    'altitude':[3158,3000,2762]})

In [21]:
state_map = {'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [22]:
dframe

city  altitude
0        Alma      3158
1  Brian Head      3000
2    Fox Park      2762

In [23]:
dframe['state'] = dframe['city'].map(state_map)

In [24]:
dframe

city  altitude     state
0        Alma      3158  Colorado
1  Brian Head      3000      Utah
2    Fox Park      2762   Wyoming

In [25]:
ser1 = Series([1,2,3,4,1,2,3,4])

In [26]:
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [27]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [28]:
ser1.replace([1,4], [100, 400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [29]:
dframe = DataFrame(np.arange(12).reshape((3, 4)),
                 index=['NY', 'LA', 'SF'],
                 columns=['A', 'B', 'C', 'D'])

In [30]:
dframe

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [31]:
dframe.index.map(str.lower)

Index(['ny', 'la', 'sf'], dtype='object')

In [32]:
dframe.index = dframe.index.map(str.lower)

In [33]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [34]:
dframe.rename(index = str.title, columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [36]:
dframe.rename(index={'ny':'NEW YORK'})

A  B   C   D
NEW YORK  0  1   2   3
la        4  5   6   7
sf        8  9  10  11

In [37]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [38]:
years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [39]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [40]:
decade_cat = pd.cut(years, decade_bins)

In [41]:
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [42]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]]
              closed='right',
              dtype='interval[int64]')

In [43]:
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [44]:
pd.cut(years, 2, precision=1)

[(1969.0, 1992.0], (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1969.0, 1992.0] < (1992.0, 2015.0]]

In [45]:
dframe = DataFrame(np.arange(4 * 4).reshape((4, 4)))

In [46]:
blender = np.random.permutation(4)

In [47]:
blender

array([2, 3, 0, 1])

In [48]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [49]:
dframe.take(blender)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7

In [50]:
box = np.array([1,2,3])

In [51]:
box

array([1, 2, 3])

In [52]:
shaker = np.random.randint(0, len(box), size=10)

In [53]:
shaker

array([0, 0, 2, 1, 1, 2, 1, 0, 0, 0])

In [54]:
hand_grabs = box.take(shaker)

In [55]:
hand_grabs

array([1, 1, 3, 2, 2, 3, 2, 1, 1, 1])